"""initial_mysql

Revision ID: 8e85e9dbbe9f
Revises: 
Create Date: 2026-07-11 06:10:51.230843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e85e9dbbe9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('push', 'call_prompt', name='alert_channel'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deepcheck_sessions',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('elder_id', sa.Uuid(), nullable=False),
    sa.Column('audio_ref', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'transcribing', 'analyzing', 'done', 'failed', name='deepcheck_status'), server_default='pending', nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('whisper_latency_ms', sa.Integer(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('spoof_score', sa.Float(), nullable=True),
    sa.Column('spoof_features', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('elder_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', name='platform'), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('app_version', sa.Text(), nullable=True),
    sa.Column('permissions_granted', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_api_key_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elders',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_status', sa.Enum('invited', 'configured', 'active', name='onboarding_status'), server_default='invited', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('evidence_packages',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('hash_chain', sa.JSON(), nullable=False),
    sa.Column('pdf_ref', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('section_65b_cert_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan_tier', sa.Enum('free', 'family_99', 'family_199', name='plan_tier'), server_default='free', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_sync_log',
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('neo4j_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardians',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('elder_id', sa.Uuid(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elder_id', 'user_id')
    )
    op.create_table('incidents',
    sa.Column('elder_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('open', 'graduated_1', 'graduated_2', 'graduated_3', 'graduated_4', 'resolved', 'false_positive', name='incident_status'), server_default='open', nullable=False),
    sa.Column('risk_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_call_log',
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scam_corpus',
    sa.Column('source', sa.Enum('press', 'advisory', 'synthetic', 'user_reported', name='scam_source'), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('red_flag_tags', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_events',
    sa.Column('elder_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('call_start', 'call_end', 'video_call_start', 'video_call_end', 'screen_share_start', 'screen_share_end', 'foreground_app', 'unknown_number', 'first_time_payee', 'banking_app_opened', name='signal_event_type'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_events_elder_time', 'signal_events', ['elder_id', 'occurred_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'family_99', 'family_199', name='plan'), nullable=False),
    sa.Column('status', sa.Enum('stub_active', 'stub_pending', name='sub_status'), nullable=False),
    sa.Column('provider', sa.Enum('razorpay', 'stripe', name='sub_provider'), nullable=True),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('adult_child', 'guardian', 'elder', 'investigator', name='role'), nullable=False),
    sa.Column('phone_e164', sa.String(length=64), nullable=False),
    sa.Column('whatsapp_opt_in', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('language_pref', sa.Enum('hi', 'en', 'ta', 'te', 'bn', 'mr', 'gu', 'kn', name='language_pref'), server_default='en', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('whatsapp_verdicts',
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('sender_phone', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'image', 'voice', 'forwarded', name='message_type'), nullable=False),
    sa.Column('raw_content_ref', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Enum('scam', 'suspicious', 'safe', 'unclear', name='verdict'), nullable=False),
    sa.Column('matched_red_flags', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('llm_provider_used', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_signals',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('signal_event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['signal_event_id'], ['signal_events.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'signal_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_signals')
    op.drop_table('whatsapp_verdicts')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_index('ix_signal_events_elder_time', table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_table('scam_corpus')
    op.drop_table('llm_call_log')
    op.drop_table('incidents')
    op.drop_table('guardians')
    op.drop_table('graph_sync_log')
    op.drop_table('families')
    op.drop_table('evidence_packages')
    op.drop_table('elders')
    op.drop_table('devices')
    op.drop_table('deepcheck_sessions')
    op.drop_table('consent_events')
    op.drop_table('alerts')
    # ### end Alembic commands ###
