package com.kavach.app.presentation.ui.auth

import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Shield
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import com.kavach.app.presentation.ui.components.KavachButton
import com.kavach.app.presentation.ui.components.KavachOutlinedButton

/**
 * Landing screen shown before authentication.
 * The user chooses to pair as Guardian or login as Elder.
 */
@Composable
fun AuthScreen(
    onNavigateToPairGuardian: () -> Unit,
    onNavigateToElderPairing: () -> Unit,
) {
    Scaffold { padding ->
        Column(
            modifier            = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(horizontal = 32.dp),
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally,
        ) {
            Icon(
                imageVector       = Icons.Default.Shield,
                contentDescription = null,
                tint              = MaterialTheme.colorScheme.primary,
                modifier          = Modifier.size(96.dp),
            )
            Spacer(Modifier.height(24.dp))
            Text(
                text      = "Kavach",
                style     = MaterialTheme.typography.displayLarge,
                color     = MaterialTheme.colorScheme.primary,
            )
            Spacer(Modifier.height(8.dp))
            Text(
                text      = "Elder Safety Shield",
                style     = MaterialTheme.typography.titleMedium,
                color     = MaterialTheme.colorScheme.onSurfaceVariant,
                textAlign = TextAlign.Center,
            )
            Spacer(Modifier.height(64.dp))
            KavachButton(
                text     = "Pair as Guardian",
                onClick  = onNavigateToPairGuardian,
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(12.dp))
            KavachOutlinedButton(
                text     = "I'm an Elder — Generate Pairing Code",
                onClick  = onNavigateToElderPairing,
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(48.dp))
            Text(
                text  = "A guardian must have a 6-digit pairing code generated by the elder's device.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                textAlign = TextAlign.Center,
            )
        }
    }
}
